// Generated by gencpp from file FP_Magang/BallCoordinates.msg
// DO NOT EDIT!


#ifndef FP_MAGANG_MESSAGE_BALLCOORDINATES_H
#define FP_MAGANG_MESSAGE_BALLCOORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace FP_Magang
{
template <class ContainerAllocator>
struct BallCoordinates_
{
  typedef BallCoordinates_<ContainerAllocator> Type;

  BallCoordinates_()
    : center_x(0.0)
    , center_y(0.0)  {
    }
  BallCoordinates_(const ContainerAllocator& _alloc)
    : center_x(0.0)
    , center_y(0.0)  {
  (void)_alloc;
    }



   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::FP_Magang::BallCoordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::FP_Magang::BallCoordinates_<ContainerAllocator> const> ConstPtr;

}; // struct BallCoordinates_

typedef ::FP_Magang::BallCoordinates_<std::allocator<void> > BallCoordinates;

typedef boost::shared_ptr< ::FP_Magang::BallCoordinates > BallCoordinatesPtr;
typedef boost::shared_ptr< ::FP_Magang::BallCoordinates const> BallCoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::FP_Magang::BallCoordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::FP_Magang::BallCoordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::FP_Magang::BallCoordinates_<ContainerAllocator1> & lhs, const ::FP_Magang::BallCoordinates_<ContainerAllocator2> & rhs)
{
  return lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::FP_Magang::BallCoordinates_<ContainerAllocator1> & lhs, const ::FP_Magang::BallCoordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace FP_Magang

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FP_Magang::BallCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FP_Magang::BallCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FP_Magang::BallCoordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c51e51b1031fa051202f8de7f01927c6";
  }

  static const char* value(const ::FP_Magang::BallCoordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc51e51b1031fa051ULL;
  static const uint64_t static_value2 = 0x202f8de7f01927c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FP_Magang/BallCoordinates";
  }

  static const char* value(const ::FP_Magang::BallCoordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 center_x\n"
"float32 center_y\n"
;
  }

  static const char* value(const ::FP_Magang::BallCoordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallCoordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::FP_Magang::BallCoordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::FP_Magang::BallCoordinates_<ContainerAllocator>& v)
  {
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FP_MAGANG_MESSAGE_BALLCOORDINATES_H
